-- The Rusti Shack: Supabase schema + product catalog load
-- Generated by scripts/generate_supabase_sql.py -- do not hand-edit, regenerate instead.

-- 1. Product catalog (mirrors the Products tab column-for-column)
drop table if exists public.products cascade;
create table public.products (
  sku text primary key,
  product_name text not null,
  category text not null,
  subcategory text not null,
  unit_cost numeric(10,2),
  unit_price numeric(10,2) not null,
  weight_kg numeric(6,2),
  supplier text,
  rental_rate numeric(10,2),
  availability text not null,
  year_introduced integer,
  parent_sku text,
  size text,
  color text,
  gender text,
  variant_type text not null
);
alter table public.products enable row level security;
create policy "Public read access" on public.products for select to anon, authenticated using (true);

insert into public.products
  (sku, product_name, category, subcategory, unit_cost, unit_price, weight_kg, supplier, rental_rate, availability, year_introduced, parent_sku, size, color, gender, variant_type)
values
  ('SNK-001', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.71, 42.99, 0.4, 'Aqualine PH', 4.78, 'Both', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('SNK-001-S-CLR', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.29, 42.99, 0.4, 'Aqualine PH', 5.36, 'Both', 2021, 'SNK-001', 'S', 'Clear', 'U', 'Variant'),
  ('SNK-001-M-CLR', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.42, 42.99, 0.4, 'Aqualine PH', 4.96, 'Both', 2021, 'SNK-001', 'M', 'Clear', 'U', 'Variant'),
  ('SNK-001-L-CLR', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.49, 42.99, 0.4, 'Aqualine PH', 4.73, 'Both', 2021, 'SNK-001', 'L', 'Clear', 'U', 'Variant'),
  ('SNK-001-S-BLK', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.31, 42.99, 0.4, 'Aqualine PH', 4.82, 'Both', 2021, 'SNK-001', 'S', 'Black', 'U', 'Variant'),
  ('SNK-001-M-BLK', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.71, 42.99, 0.4, 'Aqualine PH', 4.91, 'Both', 2021, 'SNK-001', 'M', 'Black', 'U', 'Variant'),
  ('SNK-001-L-BLK', 'Reef Explorer Snorkel Mask', 'Snorkel & Dive', 'Masks', 18.62, 42.99, 0.4, 'Aqualine PH', 5.04, 'Both', 2021, 'SNK-001', 'L', 'Black', 'U', 'Variant'),
  ('SNK-003', 'Junior Snorkel Set (Kids)', 'Snorkel & Dive', 'Sets', 16.02, 34.99, 0.55, 'Aqualine PH', 4.35, 'Both', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('SNK-003-K4-7-AQUA', 'Junior Snorkel Set (Kids)', 'Snorkel & Dive', 'Sets', 16.29, 34.99, 0.55, 'Aqualine PH', 3.87, 'Both', 2021, 'SNK-003', 'Age 4-7', 'Aqua', 'U', 'Variant'),
  ('SNK-003-K4-7-PINK', 'Junior Snorkel Set (Kids)', 'Snorkel & Dive', 'Sets', 16.28, 34.99, 0.55, 'Aqualine PH', 3.89, 'Both', 2021, 'SNK-003', 'Age 4-7', 'Pink', 'U', 'Variant'),
  ('SNK-003-K8-12-AQUA', 'Junior Snorkel Set (Kids)', 'Snorkel & Dive', 'Sets', 15.84, 34.99, 0.55, 'Aqualine PH', 3.79, 'Both', 2021, 'SNK-003', 'Age 8-12', 'Aqua', 'U', 'Variant'),
  ('SNK-003-K8-12-PINK', 'Junior Snorkel Set (Kids)', 'Snorkel & Dive', 'Sets', 15.9, 34.99, 0.55, 'Aqualine PH', 3.81, 'Both', 2021, 'SNK-003', 'Age 8-12', 'Pink', 'U', 'Variant'),
  ('SNK-005', 'Dry-Top Snorkel', 'Snorkel & Dive', 'Snorkels', 11.91, 28.5, 0.2, 'Aqualine PH', 3.02, 'Both', 2021, NULL, NULL, NULL, NULL, 'Standalone'),
  ('FIN-001', 'Open-Heel Dive Fins', 'Snorkel & Dive', 'Fins', 31.62, 79.0, 1.2, 'DeepBlue Cebu', 6.44, 'Both', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('FIN-001-S', 'Open-Heel Dive Fins', 'Snorkel & Dive', 'Fins', 32.08, 79.0, 1.2, 'DeepBlue Cebu', 6.12, 'Both', 2021, 'FIN-001', 'S (W6-7)', 'Black', 'U', 'Variant'),
  ('FIN-001-M', 'Open-Heel Dive Fins', 'Snorkel & Dive', 'Fins', 31.79, 79.0, 1.2, 'DeepBlue Cebu', 6.22, 'Both', 2021, 'FIN-001', 'M (W8-9 / M7-8)', 'Black', 'U', 'Variant'),
  ('FIN-001-L', 'Open-Heel Dive Fins', 'Snorkel & Dive', 'Fins', 31.95, 79.0, 1.2, 'DeepBlue Cebu', 6.1, 'Both', 2021, 'FIN-001', 'L (M9-10)', 'Black', 'U', 'Variant'),
  ('FIN-001-XL', 'Open-Heel Dive Fins', 'Snorkel & Dive', 'Fins', 31.62, 79.0, 1.2, 'DeepBlue Cebu', 6.42, 'Both', 2021, 'FIN-001', 'XL (M11-12)', 'Black', 'U', 'Variant'),
  ('FIN-003', 'Kids Swim Fins', 'Snorkel & Dive', 'Fins', 13.82, 29.99, 0.55, 'DeepBlue Cebu', 3.15, 'Both', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('FIN-003-S', 'Kids Swim Fins', 'Snorkel & Dive', 'Fins', 13.67, 29.99, 0.55, 'DeepBlue Cebu', 3.46, 'Both', 2021, 'FIN-003', 'Kids S', 'Aqua', 'U', 'Variant'),
  ('FIN-003-M', 'Kids Swim Fins', 'Snorkel & Dive', 'Fins', 13.8, 29.99, 0.55, 'DeepBlue Cebu', 2.64, 'Both', 2021, 'FIN-003', 'Kids M', 'Aqua', 'U', 'Variant'),
  ('BCH-002', 'Beach Ball Inflatable', 'Beach Essentials', 'Kids', 1.8, 6.99, 0.1, 'Island Imports', 1.7, 'Both', 2021, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-001', 'Sand Shovel & Bucket Set', 'Beach Essentials', 'Kids', 5.94, 14.99, 0.3, 'Island Imports', 2.05, 'Both', 2021, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-003', 'Beach Towel Tropical Print', 'Beach Essentials', 'Towels', 9.1, 24.99, 0.5, 'Island Imports', 2.71, 'Both', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('BCH-003-SUNSET', 'Beach Towel Tropical Print', 'Beach Essentials', 'Towels', 8.75, 24.99, 0.5, 'Island Imports', 3.26, 'Both', 2021, 'BCH-003', 'Standard', 'Sunset Print', 'U', 'Variant'),
  ('BCH-003-REEF', 'Beach Towel Tropical Print', 'Beach Essentials', 'Towels', 9.01, 24.99, 0.5, 'Island Imports', 2.95, 'Both', 2021, 'BCH-003', 'Standard', 'Reef Print', 'U', 'Variant'),
  ('BCH-003-PALM', 'Beach Towel Tropical Print', 'Beach Essentials', 'Towels', 8.69, 24.99, 0.5, 'Island Imports', 3.41, 'Both', 2021, 'BCH-003', 'Standard', 'Palm Print', 'U', 'Variant'),
  ('BCH-005', 'Beach Umbrella 7ft', 'Beach Essentials', 'Shade', 21.96, 54.0, 1.8, 'Island Imports', 7.74, 'Both', 2021, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-007', 'Reef-Safe Sunscreen SPF50', 'Beach Essentials', 'Sun Care', 7.68, 19.99, 0.2, 'EcoSun Manila', NULL, 'Sale only', 2021, NULL, NULL, NULL, NULL, 'Standalone'),
  ('SUR-003', 'Beginner Foam Surfboard', 'Surfing', 'Surfboards', 110.15, 279.0, 4.8, 'Siargao Boards', 15.03, 'Both', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('SUR-003-7FT', 'Beginner Foam Surfboard', 'Surfing', 'Surfboards', 109.82, 279.0, 4.8, 'Siargao Boards', 15.48, 'Both', 2021, 'SUR-003', '7''0', 'Blue', 'U', 'Variant'),
  ('SUR-003-8FT', 'Beginner Foam Surfboard', 'Surfing', 'Surfboards', 110.4, 279.0, 4.8, 'Siargao Boards', 14.75, 'Both', 2021, 'SUR-003', '8''0', 'Blue', 'U', 'Variant'),
  ('SUR-003-9FT', 'Beginner Foam Surfboard', 'Surfing', 'Surfboards', 109.74, 279.0, 4.8, 'Siargao Boards', 15.37, 'Both', 2021, 'SUR-003', '9''0', 'Blue', 'U', 'Variant'),
  ('APP-001', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.77, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-001-XS-M', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.87, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'XS', 'Teal', 'M', 'Variant'),
  ('APP-001-XS-W', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 8.28, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'XS', 'Teal', 'W', 'Variant'),
  ('APP-001-S-M', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.76, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'S', 'Teal', 'M', 'Variant'),
  ('APP-001-S-W', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.89, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'S', 'Teal', 'W', 'Variant'),
  ('APP-001-M-M', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.93, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'M', 'Teal', 'M', 'Variant'),
  ('APP-001-M-W', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.87, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'M', 'Teal', 'W', 'Variant'),
  ('APP-001-L-M', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.99, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'L', 'Teal', 'M', 'Variant'),
  ('APP-001-L-W', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.98, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'L', 'Teal', 'W', 'Variant'),
  ('APP-001-XL-M', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 8.11, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'XL', 'Teal', 'M', 'Variant'),
  ('APP-001-XL-W', 'Tide & Tempo Logo Tee', 'Apparel', 'Shirts', 7.89, 24.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2021, 'APP-001', 'XL', 'Teal', 'W', 'Variant'),
  ('SNK-002', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 24.09, 58.0, 0.45, 'Aqualine PH', 5.51, 'Both', 2022, NULL, NULL, NULL, NULL, 'Parent'),
  ('SNK-002-S-CLR', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 23.74, 58.0, 0.45, 'Aqualine PH', 6.11, 'Both', 2022, 'SNK-002', 'S', 'Clear', 'U', 'Variant'),
  ('SNK-002-M-CLR', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 23.78, 58.0, 0.45, 'Aqualine PH', 5.75, 'Both', 2022, 'SNK-002', 'M', 'Clear', 'U', 'Variant'),
  ('SNK-002-L-CLR', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 24.13, 58.0, 0.45, 'Aqualine PH', 5.91, 'Both', 2022, 'SNK-002', 'L', 'Clear', 'U', 'Variant'),
  ('SNK-002-S-BLK', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 24.28, 58.0, 0.45, 'Aqualine PH', 5.64, 'Both', 2022, 'SNK-002', 'S', 'Black', 'U', 'Variant'),
  ('SNK-002-M-BLK', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 23.79, 58.0, 0.45, 'Aqualine PH', 5.95, 'Both', 2022, 'SNK-002', 'M', 'Black', 'U', 'Variant'),
  ('SNK-002-L-BLK', 'Pro Anti-Fog Snorkel Mask', 'Snorkel & Dive', 'Masks', 23.65, 58.0, 0.45, 'Aqualine PH', 6.26, 'Both', 2022, 'SNK-002', 'L', 'Black', 'U', 'Variant'),
  ('SNK-004', 'Adult Snorkel Set', 'Snorkel & Dive', 'Sets', 27.81, 64.99, 0.85, 'Aqualine PH', 7.01, 'Both', 2022, NULL, NULL, NULL, NULL, 'Parent'),
  ('SNK-004-S', 'Adult Snorkel Set', 'Snorkel & Dive', 'Sets', 27.61, 64.99, 0.85, 'Aqualine PH', 7.25, 'Both', 2022, 'SNK-004', 'S', 'Black', 'U', 'Variant'),
  ('SNK-004-M', 'Adult Snorkel Set', 'Snorkel & Dive', 'Sets', 27.63, 64.99, 0.85, 'Aqualine PH', 7.04, 'Both', 2022, 'SNK-004', 'M', 'Black', 'U', 'Variant'),
  ('SNK-004-L', 'Adult Snorkel Set', 'Snorkel & Dive', 'Sets', 27.81, 64.99, 0.85, 'Aqualine PH', 7.04, 'Both', 2022, 'SNK-004', 'L', 'Black', 'U', 'Variant'),
  ('FIN-002', 'Travel Snorkel Fins', 'Snorkel & Dive', 'Fins', 21.87, 49.99, 0.95, 'DeepBlue Cebu', 5.38, 'Both', 2022, NULL, NULL, NULL, NULL, 'Parent'),
  ('FIN-002-S', 'Travel Snorkel Fins', 'Snorkel & Dive', 'Fins', 21.76, 49.99, 0.95, 'DeepBlue Cebu', 4.84, 'Both', 2022, 'FIN-002', 'S (W6-7)', 'Black', 'U', 'Variant'),
  ('FIN-002-M', 'Travel Snorkel Fins', 'Snorkel & Dive', 'Fins', 21.89, 49.99, 0.95, 'DeepBlue Cebu', 5.1, 'Both', 2022, 'FIN-002', 'M (W8-9 / M7-8)', 'Black', 'U', 'Variant'),
  ('FIN-002-L', 'Travel Snorkel Fins', 'Snorkel & Dive', 'Fins', 21.67, 49.99, 0.95, 'DeepBlue Cebu', 4.5, 'Both', 2022, 'FIN-002', 'L (M9-10)', 'Black', 'U', 'Variant'),
  ('FIN-002-XL', 'Travel Snorkel Fins', 'Snorkel & Dive', 'Fins', 21.7, 49.99, 0.95, 'DeepBlue Cebu', 5.1, 'Both', 2022, 'FIN-002', 'XL (M11-12)', 'Black', 'U', 'Variant'),
  ('WET-001', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.89, 109.0, 1.1, 'DeepBlue Cebu', 10.31, 'Both', 2022, NULL, NULL, NULL, NULL, 'Parent'),
  ('WET-001-S-M', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.67, 109.0, 1.1, 'DeepBlue Cebu', 9.67, 'Both', 2022, 'WET-001', 'S', 'Black', 'M', 'Variant'),
  ('WET-001-S-W', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 45.22, 109.0, 1.1, 'DeepBlue Cebu', 10.28, 'Both', 2022, 'WET-001', 'S', 'Black', 'W', 'Variant'),
  ('WET-001-M-M', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.71, 109.0, 1.1, 'DeepBlue Cebu', 10.21, 'Both', 2022, 'WET-001', 'M', 'Black', 'M', 'Variant'),
  ('WET-001-M-W', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 45.25, 109.0, 1.1, 'DeepBlue Cebu', 9.8, 'Both', 2022, 'WET-001', 'M', 'Black', 'W', 'Variant'),
  ('WET-001-L-M', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.7, 109.0, 1.1, 'DeepBlue Cebu', 9.68, 'Both', 2022, 'WET-001', 'L', 'Black', 'M', 'Variant'),
  ('WET-001-L-W', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.63, 109.0, 1.1, 'DeepBlue Cebu', 10.1, 'Both', 2022, 'WET-001', 'L', 'Black', 'W', 'Variant'),
  ('WET-001-XL-M', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.97, 109.0, 1.1, 'DeepBlue Cebu', 10.49, 'Both', 2022, 'WET-001', 'XL', 'Black', 'M', 'Variant'),
  ('WET-001-XL-W', '3mm Shorty Wetsuit', 'Snorkel & Dive', 'Wetsuits', 44.98, 109.0, 1.1, 'DeepBlue Cebu', 10.32, 'Both', 2022, 'WET-001', 'XL', 'Black', 'W', 'Variant'),
  ('WET-002', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 14.13, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, NULL, NULL, NULL, NULL, 'Parent'),
  ('WET-002-S-M', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 13.81, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'S', 'Navy', 'M', 'Variant'),
  ('WET-002-S-W', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 13.7, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'S', 'Coral', 'W', 'Variant'),
  ('WET-002-M-M', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 14.37, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'M', 'Navy', 'M', 'Variant'),
  ('WET-002-M-W', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 13.79, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'M', 'Coral', 'W', 'Variant'),
  ('WET-002-L-M', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 14.24, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'L', 'Navy', 'M', 'Variant'),
  ('WET-002-L-W', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 13.75, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'L', 'Coral', 'W', 'Variant'),
  ('WET-002-XL-M', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 14.38, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'XL', 'Navy', 'M', 'Variant'),
  ('WET-002-XL-W', 'Rashguard Long Sleeve', 'Apparel', 'Rashguards', 14.07, 32.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2022, 'WET-002', 'XL', 'Coral', 'W', 'Variant'),
  ('FSH-001', 'Saltwater Spinning Rod 7ft', 'Fishing', 'Rods', 41.68, 98.0, 0.8, 'Pacific Tackle', 7.65, 'Both', 2022, NULL, NULL, NULL, NULL, 'Standalone'),
  ('FSH-003', 'Spinning Reel 4000', 'Fishing', 'Reels', 36.01, 84.0, 0.45, 'Pacific Tackle', NULL, 'Sale only', 2022, NULL, NULL, NULL, NULL, 'Standalone'),
  ('FSH-005', 'Live Bait — Shrimp (lb)', 'Fishing', 'Bait', 2.22, 6.99, 0.45, 'Local Fishermen Co-op', NULL, 'Sale only', 2022, NULL, NULL, NULL, NULL, 'Standalone'),
  ('FSH-006', 'Live Bait — Squid (lb)', 'Fishing', 'Bait', 3.21, 7.99, 0.45, 'Local Fishermen Co-op', NULL, 'Sale only', 2022, NULL, NULL, NULL, NULL, 'Standalone'),
  ('APP-002', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.01, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-002-XS-M', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.2, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'XS', 'Sand', 'M', 'Variant'),
  ('APP-002-XS-W', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.15, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'XS', 'Sand', 'W', 'Variant'),
  ('APP-002-S-M', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.33, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'S', 'Sand', 'M', 'Variant'),
  ('APP-002-S-W', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.11, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'S', 'Sand', 'W', 'Variant'),
  ('APP-002-M-M', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 8.79, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'M', 'Sand', 'M', 'Variant'),
  ('APP-002-M-W', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.33, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'M', 'Sand', 'W', 'Variant'),
  ('APP-002-L-M', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.03, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'L', 'Sand', 'M', 'Variant'),
  ('APP-002-L-W', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 8.86, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'L', 'Sand', 'W', 'Variant'),
  ('APP-002-XL-M', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.38, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'XL', 'Sand', 'M', 'Variant'),
  ('APP-002-XL-W', 'Apo Island Souvenir Tee', 'Apparel', 'Shirts', 9.07, 26.99, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2022, 'APP-002', 'XL', 'Sand', 'W', 'Variant'),
  ('BCH-004', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 11.1, 28.0, 0.3, 'Island Imports', 3.29, 'Both', 2023, NULL, NULL, NULL, NULL, 'Parent'),
  ('BCH-004-M-BLU', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 11.06, 28.0, 0.3, 'Island Imports', 3.35, 'Both', 2023, 'BCH-004', 'M (60x120cm)', 'Blue', 'U', 'Variant'),
  ('BCH-004-L-BLU', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 11.21, 28.0, 0.3, 'Island Imports', 3.43, 'Both', 2023, 'BCH-004', 'L (80x160cm)', 'Blue', 'U', 'Variant'),
  ('BCH-004-M-CRL', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 11.05, 28.0, 0.3, 'Island Imports', 2.7, 'Both', 2023, 'BCH-004', 'M (60x120cm)', 'Coral', 'U', 'Variant'),
  ('BCH-004-L-CRL', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 10.93, 28.0, 0.3, 'Island Imports', 3.38, 'Both', 2023, 'BCH-004', 'L (80x160cm)', 'Coral', 'U', 'Variant'),
  ('BCH-004-M-BLK', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 10.9, 28.0, 0.3, 'Island Imports', 3.39, 'Both', 2023, 'BCH-004', 'M (60x120cm)', 'Black', 'U', 'Variant'),
  ('BCH-004-L-BLK', 'Microfiber Quick-Dry Towel', 'Beach Essentials', 'Towels', 11.04, 28.0, 0.3, 'Island Imports', 2.85, 'Both', 2023, 'BCH-004', 'L (80x160cm)', 'Black', 'U', 'Variant'),
  ('BCH-006', 'Pop-Up Beach Tent', 'Beach Essentials', 'Shade', 37.74, 89.0, 2.5, 'Island Imports', 10.4, 'Both', 2023, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-008', 'After-Sun Aloe Gel', 'Beach Essentials', 'Sun Care', 5.31, 13.99, 0.25, 'EcoSun Manila', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-012', 'Cooler Bag Insulated 24L', 'Beach Essentials', 'Coolers', 24.3, 58.0, 1.2, 'Island Imports', 4.85, 'Both', 2023, NULL, NULL, NULL, NULL, 'Parent'),
  ('BCH-012-16L', 'Cooler Bag Insulated 24L', 'Beach Essentials', 'Coolers', 18.28, 44.0, 0.9, 'Island Imports', 4.68, 'Both', 2023, 'BCH-012', '16 L', 'Blue', 'U', 'Variant'),
  ('BCH-012-24L', 'Cooler Bag Insulated 24L', 'Beach Essentials', 'Coolers', 24.29, 58.0, 1.2, 'Island Imports', 4.77, 'Both', 2023, 'BCH-012', '24 L', 'Blue', 'U', 'Variant'),
  ('BCH-012-40L', 'Cooler Bag Insulated 24L', 'Beach Essentials', 'Coolers', 35.97, 79.0, 1.8, 'Island Imports', 5.09, 'Both', 2023, 'BCH-012', '40 L', 'Blue', 'U', 'Variant'),
  ('APP-003', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 17.6, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-003-28', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 17.62, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '28', 'Navy', 'M', 'Variant'),
  ('APP-003-30', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 18.17, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '30', 'Navy', 'M', 'Variant'),
  ('APP-003-32', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 17.65, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '32', 'Navy', 'M', 'Variant'),
  ('APP-003-34', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 18.01, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '34', 'Navy', 'M', 'Variant'),
  ('APP-003-36', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 17.7, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '36', 'Navy', 'M', 'Variant'),
  ('APP-003-38', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 18.06, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '38', 'Navy', 'M', 'Variant'),
  ('APP-003-40', 'Boardshorts — Mens', 'Apparel', 'Bottoms', 17.94, 44.99, 0.3, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-003', '40', 'Navy', 'M', 'Variant'),
  ('APP-004', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.74, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-004-XS-COR', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.01, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XS', 'Coral', 'W', 'Variant'),
  ('APP-004-XS-AQU', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.75, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XS', 'Aqua', 'W', 'Variant'),
  ('APP-004-XS-BLA', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.15, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XS', 'Black', 'W', 'Variant'),
  ('APP-004-XS-TRO', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.79, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XS', 'Tropical Print', 'W', 'Variant'),
  ('APP-004-S-COR', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.71, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'S', 'Coral', 'W', 'Variant'),
  ('APP-004-S-AQU', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.87, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'S', 'Aqua', 'W', 'Variant'),
  ('APP-004-S-BLA', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.8, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'S', 'Black', 'W', 'Variant'),
  ('APP-004-S-TRO', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.68, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'S', 'Tropical Print', 'W', 'Variant'),
  ('APP-004-M-COR', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.38, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'M', 'Coral', 'W', 'Variant'),
  ('APP-004-M-AQU', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.11, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'M', 'Aqua', 'W', 'Variant'),
  ('APP-004-M-BLA', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.23, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'M', 'Black', 'W', 'Variant'),
  ('APP-004-M-TRO', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.4, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'M', 'Tropical Print', 'W', 'Variant'),
  ('APP-004-L-COR', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.17, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'L', 'Coral', 'W', 'Variant'),
  ('APP-004-L-AQU', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.24, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'L', 'Aqua', 'W', 'Variant'),
  ('APP-004-L-BLA', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.11, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'L', 'Black', 'W', 'Variant'),
  ('APP-004-L-TRO', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.36, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'L', 'Tropical Print', 'W', 'Variant'),
  ('APP-004-XL-COR', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.8, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XL', 'Coral', 'W', 'Variant'),
  ('APP-004-XL-AQU', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.35, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XL', 'Aqua', 'W', 'Variant'),
  ('APP-004-XL-BLA', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 22.3, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XL', 'Black', 'W', 'Variant'),
  ('APP-004-XL-TRO', 'Bikini Set — Womens', 'Apparel', 'Swimwear', 21.84, 54.0, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-004', 'XL', 'Tropical Print', 'W', 'Variant'),
  ('APP-005', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.13, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-005-S-BLA', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.17, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'S', 'Black', 'W', 'Variant'),
  ('APP-005-S-NAV', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.2, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'S', 'Navy', 'W', 'Variant'),
  ('APP-005-S-COR', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.21, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'S', 'Coral', 'W', 'Variant'),
  ('APP-005-M-BLA', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 23.66, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'M', 'Black', 'W', 'Variant'),
  ('APP-005-M-NAV', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.37, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'M', 'Navy', 'W', 'Variant'),
  ('APP-005-M-COR', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.17, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'M', 'Coral', 'W', 'Variant'),
  ('APP-005-L-BLA', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 23.89, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'L', 'Black', 'W', 'Variant'),
  ('APP-005-L-NAV', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.18, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'L', 'Navy', 'W', 'Variant'),
  ('APP-005-L-COR', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.38, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'L', 'Coral', 'W', 'Variant'),
  ('APP-005-XL-BLA', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.1, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'XL', 'Black', 'W', 'Variant'),
  ('APP-005-XL-NAV', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 23.7, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'XL', 'Navy', 'W', 'Variant'),
  ('APP-005-XL-COR', 'One-Piece Swimsuit', 'Apparel', 'Swimwear', 24.1, 58.0, 0.25, 'Manila Surf Co', NULL, 'Sale only', 2023, 'APP-005', 'XL', 'Coral', 'W', 'Variant'),
  ('APP-007', 'Flip Flops Tropical', 'Apparel', 'Footwear', 4.92, 14.99, 0.3, 'Island Imports', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-007-W6-7', 'Flip Flops Tropical', 'Apparel', 'Footwear', 4.81, 14.99, 0.3, 'Island Imports', NULL, 'Sale only', 2023, 'APP-007', 'W6-7', 'Tropical', 'W', 'Variant'),
  ('APP-007-W8-9', 'Flip Flops Tropical', 'Apparel', 'Footwear', 4.89, 14.99, 0.3, 'Island Imports', NULL, 'Sale only', 2023, 'APP-007', 'W8-9', 'Tropical', 'W', 'Variant'),
  ('APP-007-M9-10', 'Flip Flops Tropical', 'Apparel', 'Footwear', 4.92, 14.99, 0.3, 'Island Imports', NULL, 'Sale only', 2023, 'APP-007', 'M9-10', 'Tropical', 'M', 'Variant'),
  ('APP-007-M11-12', 'Flip Flops Tropical', 'Apparel', 'Footwear', 4.62, 14.99, 0.3, 'Island Imports', NULL, 'Sale only', 2023, 'APP-007', 'M11-12', 'Tropical', 'M', 'Variant'),
  ('APP-007-K2-4', 'Flip Flops Tropical', 'Apparel', 'Footwear', 5.2, 14.99, 0.3, 'Island Imports', NULL, 'Sale only', 2023, 'APP-007', 'K2-4', 'Tropical', 'U', 'Variant'),
  ('FSH-007', 'Lure Pack Tropical (12pc)', 'Fishing', 'Tackle', 9.38, 22.99, 0.2, 'Pacific Tackle', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Standalone'),
  ('FSH-008', 'Cast Net 8ft', 'Fishing', 'Nets', 17.92, 45.0, 0.9, 'Local Fishermen Co-op', NULL, 'Sale only', 2023, NULL, NULL, NULL, NULL, 'Standalone'),
  ('SUR-001', '7''2 Funboard Surfboard', 'Surfing', 'Surfboards', 180.22, 449.0, 5.5, 'Siargao Boards', 25.42, 'Both', 2024, NULL, NULL, NULL, NULL, 'Standalone'),
  ('SUR-002', '9''0 Longboard Surfboard', 'Surfing', 'Surfboards', 239.79, 599.0, 7.2, 'Siargao Boards', 29.91, 'Both', 2024, NULL, NULL, NULL, NULL, 'Standalone'),
  ('SUR-004', 'Surf Leash 8ft', 'Surfing', 'Accessories', 8.14, 22.5, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2024, NULL, NULL, NULL, NULL, 'Parent'),
  ('SUR-004-6FT', 'Surf Leash 8ft', 'Surfing', 'Accessories', 7.66, 22.5, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2024, 'SUR-004', '6 ft', 'Black', 'U', 'Variant'),
  ('SUR-004-7FT', 'Surf Leash 8ft', 'Surfing', 'Accessories', 7.82, 22.5, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2024, 'SUR-004', '7 ft', 'Black', 'U', 'Variant'),
  ('SUR-004-8FT', 'Surf Leash 8ft', 'Surfing', 'Accessories', 8.16, 22.5, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2024, 'SUR-004', '8 ft', 'Black', 'U', 'Variant'),
  ('SUR-004-9FT', 'Surf Leash 8ft', 'Surfing', 'Accessories', 7.64, 22.5, 0.2, 'Manila Surf Co', NULL, 'Sale only', 2024, 'SUR-004', '9 ft', 'Black', 'U', 'Variant'),
  ('SUR-006', 'Skim Board Pro', 'Surfing', 'Skimboards', 37.87, 89.0, 1.8, 'Siargao Boards', 11.62, 'Both', 2024, NULL, NULL, NULL, NULL, 'Parent'),
  ('SUR-006-YTH', 'Skim Board Pro', 'Surfing', 'Skimboards', 38.3, 89.0, 1.8, 'Siargao Boards', 12.11, 'Both', 2024, 'SUR-006', 'Youth', 'Tropical', 'U', 'Variant'),
  ('SUR-006-ADL', 'Skim Board Pro', 'Surfing', 'Skimboards', 38.21, 89.0, 1.8, 'Siargao Boards', 11.8, 'Both', 2024, 'SUR-006', 'Adult', 'Tropical', 'U', 'Variant'),
  ('KIT-002', 'Kitesurf Harness', 'Surfing', 'Kitesurf', 54.67, 139.0, 1.4, 'WindRider Asia', NULL, 'Sale only', 2024, NULL, NULL, NULL, NULL, 'Parent'),
  ('KIT-002-S', 'Kitesurf Harness', 'Surfing', 'Kitesurf', 54.8, 139.0, 1.4, 'WindRider Asia', NULL, 'Sale only', 2024, 'KIT-002', 'S', 'Black', 'U', 'Variant'),
  ('KIT-002-M', 'Kitesurf Harness', 'Surfing', 'Kitesurf', 54.73, 139.0, 1.4, 'WindRider Asia', NULL, 'Sale only', 2024, 'KIT-002', 'M', 'Black', 'U', 'Variant'),
  ('KIT-002-L', 'Kitesurf Harness', 'Surfing', 'Kitesurf', 55.36, 139.0, 1.4, 'WindRider Asia', NULL, 'Sale only', 2024, 'KIT-002', 'L', 'Black', 'U', 'Variant'),
  ('KIT-002-XL', 'Kitesurf Harness', 'Surfing', 'Kitesurf', 55.23, 139.0, 1.4, 'WindRider Asia', NULL, 'Sale only', 2024, 'KIT-002', 'XL', 'Black', 'U', 'Variant'),
  ('FSH-002', 'Telescopic Travel Rod', 'Fishing', 'Rods', 27.83, 64.99, 0.55, 'Pacific Tackle', 6.08, 'Both', 2024, NULL, NULL, NULL, NULL, 'Standalone'),
  ('FSH-004', 'Tackle Box Deluxe', 'Fishing', 'Tackle', 22.14, 49.99, 1.1, 'Pacific Tackle', NULL, 'Sale only', 2024, NULL, NULL, NULL, NULL, 'Standalone'),
  ('APP-006', 'UV Hat Wide Brim', 'Apparel', 'Hats', 11.02, 28.0, 0.15, 'Manila Surf Co', NULL, 'Sale only', 2024, NULL, NULL, NULL, NULL, 'Parent'),
  ('APP-006-SM-NAT', 'UV Hat Wide Brim', 'Apparel', 'Hats', 11.28, 28.0, 0.15, 'Manila Surf Co', NULL, 'Sale only', 2024, 'APP-006', 'S/M', 'Natural', 'U', 'Variant'),
  ('APP-006-SM-BLK', 'UV Hat Wide Brim', 'Apparel', 'Hats', 11.33, 28.0, 0.15, 'Manila Surf Co', NULL, 'Sale only', 2024, 'APP-006', 'S/M', 'Black', 'U', 'Variant'),
  ('APP-006-LXL-NAT', 'UV Hat Wide Brim', 'Apparel', 'Hats', 11.06, 28.0, 0.15, 'Manila Surf Co', NULL, 'Sale only', 2024, 'APP-006', 'L/XL', 'Natural', 'U', 'Variant'),
  ('APP-006-LXL-BLK', 'UV Hat Wide Brim', 'Apparel', 'Hats', 10.97, 28.0, 0.15, 'Manila Surf Co', NULL, 'Sale only', 2024, 'APP-006', 'L/XL', 'Black', 'U', 'Variant'),
  ('KIT-001', 'Beginner Kitesurf Kit', 'Surfing', 'Kitesurf', 420.3, 1099.0, 11.0, 'WindRider Asia', NULL, 'Sale only', 2025, NULL, NULL, NULL, NULL, 'Parent'),
  ('KIT-001-7M', 'Beginner Kitesurf Kit', 'Surfing', 'Kitesurf', 419.77, 1099.0, 11.0, 'WindRider Asia', NULL, 'Sale only', 2025, 'KIT-001', '7 m2', 'Red', 'U', 'Variant'),
  ('KIT-001-9M', 'Beginner Kitesurf Kit', 'Surfing', 'Kitesurf', 420.02, 1099.0, 11.0, 'WindRider Asia', NULL, 'Sale only', 2025, 'KIT-001', '9 m2', 'Blue', 'U', 'Variant'),
  ('KIT-001-12M', 'Beginner Kitesurf Kit', 'Surfing', 'Kitesurf', 419.83, 1099.0, 11.0, 'WindRider Asia', NULL, 'Sale only', 2025, 'KIT-001', '12 m2', 'Yellow', 'U', 'Variant'),
  ('SUR-005', 'Surf Wax Tropical', 'Surfing', 'Accessories', 1.85, 5.99, 0.1, 'Manila Surf Co', NULL, 'Sale only', 2025, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-009', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 14.12, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, NULL, NULL, NULL, NULL, 'Parent'),
  ('BCH-009-AVI-BLK', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 14.39, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, 'BCH-009', 'One Size', 'Aviator/Black', 'M', 'Variant'),
  ('BCH-009-AVI-GLD', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 13.74, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, 'BCH-009', 'One Size', 'Aviator/Gold', 'U', 'Variant'),
  ('BCH-009-WAY-BLK', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 14.21, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, 'BCH-009', 'One Size', 'Wayfarer/Black', 'U', 'Variant'),
  ('BCH-009-WAY-TOR', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 14.28, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, 'BCH-009', 'One Size', 'Wayfarer/Tortoise', 'U', 'Variant'),
  ('BCH-009-SPT-BLK', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 14.31, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, 'BCH-009', 'One Size', 'Sport/Black', 'M', 'Variant'),
  ('BCH-009-CAT-TOR', 'Polarized Sunglasses', 'Beach Essentials', 'Eyewear', 14.09, 39.99, 0.1, 'Island Imports', NULL, 'Sale only', 2025, 'BCH-009', 'One Size', 'Cat-Eye/Tortoise', 'W', 'Variant'),
  ('BCH-010', 'Waterproof Phone Pouch', 'Beach Essentials', 'Accessories', 4.11, 12.99, 0.05, 'Island Imports', NULL, 'Sale only', 2025, NULL, NULL, NULL, NULL, 'Standalone'),
  ('BCH-011', 'Reef Walker Water Shoes', 'Beach Essentials', 'Footwear', 16.38, 38.0, 0.4, 'Island Imports', 3.07, 'Both', 2025, NULL, NULL, NULL, NULL, 'Parent'),
  ('BCH-011-W6-7', 'Reef Walker Water Shoes', 'Beach Essentials', 'Footwear', 15.82, 38.0, 0.4, 'Island Imports', 2.74, 'Both', 2025, 'BCH-011', 'W6-7', 'Black', 'W', 'Variant'),
  ('BCH-011-W8-9', 'Reef Walker Water Shoes', 'Beach Essentials', 'Footwear', 15.72, 38.0, 0.4, 'Island Imports', 2.62, 'Both', 2025, 'BCH-011', 'W8-9', 'Black', 'W', 'Variant'),
  ('BCH-011-M9-10', 'Reef Walker Water Shoes', 'Beach Essentials', 'Footwear', 15.8, 38.0, 0.4, 'Island Imports', 2.5, 'Both', 2025, 'BCH-011', 'M9-10', 'Black', 'M', 'Variant'),
  ('BCH-011-M11-12', 'Reef Walker Water Shoes', 'Beach Essentials', 'Footwear', 15.89, 38.0, 0.4, 'Island Imports', 2.74, 'Both', 2025, 'BCH-011', 'M11-12', 'Black', 'M', 'Variant'),
  ('BCH-011-K2-4', 'Reef Walker Water Shoes', 'Beach Essentials', 'Footwear', 15.63, 38.0, 0.4, 'Island Imports', 2.72, 'Both', 2025, 'BCH-011', 'Kids 2-4', 'Aqua', 'U', 'Variant');

-- 2. Customers and Orders tables (empty for now; the web checkout fills these in)
drop table if exists public."OrderLines" cascade;
drop table if exists public."Orders" cascade;
drop table if exists public."Customers_Contact" cascade;
drop table if exists public."Customers_Core" cascade;

create table public."Customers_Core" (
  "CustomerID" text primary key,
  "FirstName" text not null,
  "LastName" text not null,
  "CustomerType" text not null,
  "JoinDate" date not null,
  "City" text,
  "Country" text
);

create table public."Customers_Contact" (
  "CustomerID" text primary key references public."Customers_Core"("CustomerID"),
  "Email" text not null,
  "Phone" text,
  "LoyaltyMember" boolean not null default false,
  "StreetAddress" text,
  "Region" text,
  "PostalCode" text
);

create table public."Orders" (
  "OrderID" text primary key,
  "OrderDate" date not null,
  "CustID" text references public."Customers_Core"("CustomerID"),
  "LocationID" text not null,
  "SalesAssociate" text not null,
  "Channel" text not null,
  "ShippingFee" numeric(10,2) not null,
  "OrderTotal" numeric(10,2) not null,
  "PaymentMethod" text not null
);

create table public."OrderLines" (
  "OrderID" text references public."Orders"("OrderID"),
  "LineNumber" integer not null,
  "ProductCode" text not null,
  "Quantity" integer not null,
  "UnitPrice" numeric(10,2) not null,
  "DiscountPct" numeric(5,2) not null default 0,
  "LineRevenue" numeric(10,2) not null,
  "LineCost" numeric(10,2),
  "EffectiveDiscountAmount" numeric(10,2) not null default 0,
  primary key ("OrderID", "LineNumber")
);

alter table public."Customers_Core" enable row level security;
alter table public."Customers_Contact" enable row level security;
alter table public."Orders" enable row level security;
alter table public."OrderLines" enable row level security;
-- No select/insert policies for anon/authenticated on purpose: these tables
-- hold customer PII and financial data. All reads/writes to them happen
-- through server-side code using the service_role key (checkout, after
-- Stripe confirms payment; the manager page). See SECURITY.md.


-- 3. ID sequences reserved for the website (Rusti's highest existing IDs
-- are C03500 and ORD066198 as of this dataset;
-- these start well above that so web and in-store IDs never collide).
create sequence public.web_customer_id_seq start 10001;
create sequence public.web_order_id_seq start 100001;

create function public.next_web_customer_id() returns text
  language sql as $$
    select 'C' || lpad(nextval('public.web_customer_id_seq')::text, 5, '0');
  $$;

create function public.next_web_order_id() returns text
  language sql as $$
    select 'ORD' || lpad(nextval('public.web_order_id_seq')::text, 6, '0');
  $$;

revoke execute on function public.next_web_customer_id() from public, anon, authenticated;
revoke execute on function public.next_web_order_id() from public, anon, authenticated;
grant execute on function public.next_web_customer_id() to service_role;
grant execute on function public.next_web_order_id() to service_role;

-- 4. Idempotency guard: one row per Stripe Checkout Session, so refreshing
-- the confirmation page (or a curious visitor replaying the URL) can never
-- create a duplicate order. See SECURITY.md section on payment verification.
create table public.stripe_sessions (
  stripe_session_id text primary key,
  "OrderID" text not null references public."Orders"("OrderID"),
  created_at timestamptz not null default now()
);
alter table public.stripe_sessions enable row level security;
-- No anon policies: written only by server-side code with the service_role key.
