import "server-only";
import {
  getMonthlyPerformance,
  getProductPerformance,
  getInventoryReorderView,
  getCustomerSummary,
  getPromoPerformance,
  getStaffPerformance,
  getSeasonalPerformance,
  getRentalVsSales,
} from "./analytics-data";

/**
 * Builds the ONLY data the AI assistant ever sees: pre-computed,
 * pre-aggregated summaries, already produced by real database queries
 * elsewhere in this app (never generated by the model). Nothing here is
 * an individual customer record -- customer data is rolled up into
 * segment-level counts (by type, by country), never a name, email,
 * phone, or address. See SECURITY.md and the Part D guardrails.
 */
export async function buildAssistantContext() {
  const [monthly, products, inventory, customers, promos, staff, seasonal, rentalVsSales] =
    await Promise.all([
      getMonthlyPerformance(),
      getProductPerformance(),
      getInventoryReorderView(),
      getCustomerSummary(),
      getPromoPerformance(),
      getStaffPerformance(),
      getSeasonalPerformance(),
      getRentalVsSales(),
    ]);

  const customersByType = new Map<string, { count: number; totalRevenue: number; repeat: number }>();
  const customersByCountry = new Map<string, { count: number; totalRevenue: number }>();
  for (const c of customers) {
    const t = customersByType.get(c.customerType) ?? { count: 0, totalRevenue: 0, repeat: 0 };
    t.count += 1;
    t.totalRevenue += c.lifetimeRevenue;
    if (c.orderCount > 1) t.repeat += 1;
    customersByType.set(c.customerType, t);

    const country = c.country || "Unknown";
    const cty = customersByCountry.get(country) ?? { count: 0, totalRevenue: 0 };
    cty.count += 1;
    cty.totalRevenue += c.lifetimeRevenue;
    customersByCountry.set(country, cty);
  }

  const skuAgg = new Map<string, { unitsSold: number; unitsRented: number; saleRevenue: number; rentalRevenue: number }>();
  for (const r of rentalVsSales) {
    const e = skuAgg.get(r.sku) ?? { unitsSold: 0, unitsRented: 0, saleRevenue: 0, rentalRevenue: 0 };
    e.unitsSold += r.unitsSold;
    e.unitsRented += r.unitsRented;
    e.saleRevenue += r.saleRevenue;
    e.rentalRevenue += r.rentalRevenue;
    skuAgg.set(r.sku, e);
  }

  const SEASON_MONTHS: Record<string, number> = { "Dry Peak": 5, Shoulder: 1, Typhoon: 6 };
  const seasonAgg = new Map<string, { revenue: number; margin: number; years: Set<number> }>();
  for (const s of seasonal) {
    const e = seasonAgg.get(s.season) ?? { revenue: 0, margin: 0, years: new Set<number>() };
    e.revenue += s.revenue;
    e.margin += s.margin;
    e.years.add(s.year);
    seasonAgg.set(s.season, e);
  }

  return {
    note: "All figures are USD. 'month' fields are YYYY-MM-01. This is the shop's complete, real transaction history plus current-day web orders -- there is no other data source.",
    monthlyPerformance: monthly.map((m) => ({
      month: m.month,
      revenue: m.revenue,
      cost: m.cost,
      margin: m.margin,
      orderCount: m.orderCount,
      unitsSold: m.unitsSold,
    })),
    topProductsByMargin: products.slice(0, 20).map((p) => ({
      sku: p.sku,
      name: p.productName,
      category: p.category,
      unitsSold: p.unitsSold,
      revenue: p.revenue,
      margin: p.margin,
      marginPct: p.marginPct,
    })),
    lowestMarginProducts: [...products]
      .filter((p) => p.marginPct !== null)
      .sort((a, b) => (a.marginPct ?? 0) - (b.marginPct ?? 0))
      .slice(0, 10)
      .map((p) => ({ sku: p.sku, name: p.productName, revenue: p.revenue, marginPct: p.marginPct })),
    inventoryNeedingReorder: inventory
      .filter((r) => r.needsReorder)
      .slice(0, 20)
      .map((r) => ({ sku: r.sku, name: r.productName, availableForSale: r.availableForSale, reorderPoint: r.reorderPoint, daysOfStockLeft: r.daysOfStockLeft })),
    customerSegmentsByType: Array.from(customersByType.entries()).map(([type, v]) => ({
      customerType: type,
      customerCount: v.count,
      totalLifetimeRevenue: Math.round(v.totalRevenue),
      repeatCustomers: v.repeat,
      repeatRatePct: v.count > 0 ? Math.round((v.repeat / v.count) * 100) : 0,
    })),
    customerSegmentsByCountry: Array.from(customersByCountry.entries())
      .sort((a, b) => b[1].totalRevenue - a[1].totalRevenue)
      .slice(0, 15)
      .map(([country, v]) => ({ country, customerCount: v.count, totalLifetimeRevenue: Math.round(v.totalRevenue) })),
    promotions: promos.slice(0, 20).map((p) => ({
      code: p.promoCode,
      name: p.promoName,
      type: p.promoType,
      ordersUsing: p.ordersUsing,
      totalDiscountGiven: p.totalDiscount,
      revenueFromOrders: p.revenueFromOrders,
    })),
    staffPerformance: staff.map((s) => ({
      name: s.employeeName,
      role: s.role,
      ordersHandled: s.ordersHandled,
      orderRevenue: s.orderRevenue,
      rentalsHandled: s.rentalsHandled,
      rentalRevenue: s.rentalRevenue,
    })),
    seasonalAvgPerMonth: Array.from(seasonAgg.entries()).map(([season, v]) => {
      const monthsObserved = (SEASON_MONTHS[season] ?? 1) * v.years.size;
      return {
        season,
        avgRevenuePerMonth: monthsObserved > 0 ? Math.round(v.revenue / monthsObserved) : 0,
        avgMarginPerMonth: monthsObserved > 0 ? Math.round(v.margin / monthsObserved) : 0,
      };
    }),
    rentalVsSalesBySku: Array.from(skuAgg.entries())
      .filter(([, v]) => v.unitsRented > 0 || v.unitsSold > 0)
      .sort((a, b) => b[1].saleRevenue + b[1].rentalRevenue - (a[1].saleRevenue + a[1].rentalRevenue))
      .slice(0, 20)
      .map(([sku, v]) => ({ sku, ...v })),
  };
}
