"""
Generates supabase/migration.sql: the products table (mirroring the
Products tab of data/The_Rusti_Shack_Dataset.xlsx column-for-column) plus
the four empty order-side tables from Rusti's Orders/OrderLines/Customers
sheets. Paste the output into the Supabase SQL Editor and run it once.

    python3 scripts/generate_supabase_sql.py
"""
import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sql_str(value):
    if pd.isna(value):
        return "NULL"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def sql_num(value):
    if pd.isna(value):
        return "NULL"
    return str(value)


def sql_int(value):
    if pd.isna(value):
        return "NULL"
    return str(int(value))


def main():
    df = pd.read_excel(
        os.path.join(ROOT, "data", "The_Rusti_Shack_Dataset.xlsx"), sheet_name="Products"
    )

    lines = []
    lines.append("-- The Rusti Shack: Supabase schema + product catalog load")
    lines.append("-- Generated by scripts/generate_supabase_sql.py -- do not hand-edit, regenerate instead.")
    lines.append("")
    lines.append("-- 1. Product catalog (mirrors the Products tab column-for-column)")
    lines.append("drop table if exists public.products cascade;")
    lines.append("""create table public.products (
  sku text primary key,
  product_name text not null,
  category text not null,
  subcategory text not null,
  unit_cost numeric(10,2),
  unit_price numeric(10,2) not null,
  weight_kg numeric(6,2),
  supplier text,
  rental_rate numeric(10,2),
  availability text not null,
  year_introduced integer,
  parent_sku text,
  size text,
  color text,
  gender text,
  variant_type text not null
);""")
    lines.append("alter table public.products enable row level security;")
    lines.append(
        'create policy "Public read access" on public.products for select to anon, authenticated using (true);'
    )
    lines.append("")
    lines.append("insert into public.products")
    lines.append(
        "  (sku, product_name, category, subcategory, unit_cost, unit_price, weight_kg, "
        "supplier, rental_rate, availability, year_introduced, parent_sku, size, color, gender, variant_type)"
    )
    lines.append("values")

    value_rows = []
    for _, r in df.iterrows():
        value_rows.append(
            "  ("
            + ", ".join(
                [
                    sql_str(r["SKU"]),
                    sql_str(r["ProductName"]),
                    sql_str(r["Category"]),
                    sql_str(r["Subcategory"]),
                    sql_num(r["UnitCost"]),
                    sql_num(r["UnitPrice"]),
                    sql_num(r["Weight_kg"]),
                    sql_str(r["Supplier"]),
                    sql_num(r["RentalRate"]),
                    sql_str(r["Availability"]),
                    sql_int(r["YearIntroduced"]),
                    sql_str(r["ParentSKU"]),
                    sql_str(r["Size"]),
                    sql_str(r["Color"]),
                    sql_str(r["Gender"]),
                    sql_str(r["VariantType"]),
                ]
            )
            + ")"
        )
    lines.append(",\n".join(value_rows) + ";")

    lines.append("")
    lines.append("-- 2. Customers and Orders tables (empty for now; the web checkout fills these in)")
    lines.append('drop table if exists public."OrderLines" cascade;')
    lines.append('drop table if exists public."Orders" cascade;')
    lines.append('drop table if exists public."Customers_Contact" cascade;')
    lines.append('drop table if exists public."Customers_Core" cascade;')
    lines.append("""
create table public."Customers_Core" (
  "CustomerID" text primary key,
  "FirstName" text not null,
  "LastName" text not null,
  "CustomerType" text not null,
  "JoinDate" date not null,
  "City" text,
  "Country" text
);

create table public."Customers_Contact" (
  "CustomerID" text primary key references public."Customers_Core"("CustomerID"),
  "Email" text not null,
  "Phone" text,
  "LoyaltyMember" boolean not null default false,
  "StreetAddress" text,
  "Region" text,
  "PostalCode" text
);

create table public."Orders" (
  "OrderID" text primary key,
  "OrderDate" date not null,
  "CustID" text references public."Customers_Core"("CustomerID"),
  "LocationID" text not null,
  "SalesAssociate" text not null,
  "Channel" text not null,
  "ShippingFee" numeric(10,2) not null,
  "OrderTotal" numeric(10,2) not null,
  "PaymentMethod" text not null
);

create table public."OrderLines" (
  "OrderID" text references public."Orders"("OrderID"),
  "LineNumber" integer not null,
  "ProductCode" text not null,
  "Quantity" integer not null,
  "UnitPrice" numeric(10,2) not null,
  "DiscountPct" numeric(5,2) not null default 0,
  "LineRevenue" numeric(10,2) not null,
  "LineCost" numeric(10,2),
  "EffectiveDiscountAmount" numeric(10,2) not null default 0,
  primary key ("OrderID", "LineNumber")
);

alter table public."Customers_Core" enable row level security;
alter table public."Customers_Contact" enable row level security;
alter table public."Orders" enable row level security;
alter table public."OrderLines" enable row level security;
-- No select/insert policies for anon/authenticated on purpose: these tables
-- hold customer PII and financial data. All reads/writes to them happen
-- through server-side code using the service_role key (checkout, after
-- Stripe confirms payment; the manager page). See SECURITY.md.
""")

    # 3. ID sequences reserved for the website, well above Rusti's existing
    # highest IDs, so web-generated IDs can never collide with her sheets.
    customers_core = pd.read_excel(
        os.path.join(ROOT, "data", "The_Rusti_Shack_Dataset.xlsx"), sheet_name="Customers_Core"
    )
    orders_sheet = pd.read_excel(
        os.path.join(ROOT, "data", "The_Rusti_Shack_Dataset.xlsx"), sheet_name="Orders"
    )
    max_customer_num = customers_core["CustomerID"].str.replace("C", "", regex=False).astype(int).max()
    max_order_num = orders_sheet["OrderID"].str.replace("ORD", "", regex=False).astype(int).max()
    customer_seq_start = ((max_customer_num // 10000) + 1) * 10000 + 1
    order_seq_start = ((max_order_num // 100000) + 1) * 100000 + 1

    lines.append(f"""
-- 3. ID sequences reserved for the website (Rusti's highest existing IDs
-- are C{max_customer_num:05d} and ORD{max_order_num:06d} as of this dataset;
-- these start well above that so web and in-store IDs never collide).
create sequence public.web_customer_id_seq start {customer_seq_start};
create sequence public.web_order_id_seq start {order_seq_start};

create function public.next_web_customer_id() returns text
  language sql as $$
    select 'C' || lpad(nextval('public.web_customer_id_seq')::text, 5, '0');
  $$;

create function public.next_web_order_id() returns text
  language sql as $$
    select 'ORD' || lpad(nextval('public.web_order_id_seq')::text, 6, '0');
  $$;

revoke execute on function public.next_web_customer_id() from public, anon, authenticated;
revoke execute on function public.next_web_order_id() from public, anon, authenticated;
grant execute on function public.next_web_customer_id() to service_role;
grant execute on function public.next_web_order_id() to service_role;

-- 4. Idempotency guard: one row per Stripe Checkout Session, so refreshing
-- the confirmation page (or a curious visitor replaying the URL) can never
-- create a duplicate order. See SECURITY.md section on payment verification.
create table public.stripe_sessions (
  stripe_session_id text primary key,
  "OrderID" text not null references public."Orders"("OrderID"),
  created_at timestamptz not null default now()
);
alter table public.stripe_sessions enable row level security;
-- No anon policies: written only by server-side code with the service_role key.
""")

    out_dir = os.path.join(ROOT, "supabase")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "migration.sql")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path} ({len(df)} product rows)")


if __name__ == "__main__":
    main()
